# my-project/docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./my-backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    env_file:
      - ./my-backend/.env
    restart: unless-stopped

  frontend:
    build: ./my-frontend
    container_name: react-frontend
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - backend
    restart: unless-stopped